In [1]:
import numpy as np


In [2]:
a = np.random.randint(0,10,20)
print(a)


[6 2 6 3 9 5 9 6 7 3 0 0 5 3 2 2 1 4 3 6]


In [3]:
print(np.sum(a))


82


In [4]:
print(np.min(a))


0


In [5]:
print(np.max(a))


9


In [6]:
big_array = np.random.rand(1000*1000)
%timeit sum(big_array)


71.5 ms ± 2.09 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
%timeit np.sum(big_array)


971 µs ± 24.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [9]:
b = np.random.randint(0, 10, (3, 4))
print(b)


[[3 1 7 8]
 [9 4 0 6]
 [6 2 5 9]]


In [12]:
print(np.sum(b))


60


In [15]:
b.min(axis=0)


array([3, 1, 0, 6], dtype=int32)

In [16]:
b.max(axis=1)


array([8, 9, 9], dtype=int32)

In [17]:
heights = np.array([[194, 185, 183, 184, 178, 178, 190, 187, 187, 179, 186],
                    [192, 173, 194, 184, 170, 189, 170, 170, 176, 173, 185]])
print('Iran vs Spain')


Iran vs Spain


In [20]:
print('Mean height:' , heights.mean(axis=1))


Mean height: [184.63636364 179.63636364]


In [21]:
print('Standard deviation:' , heights.std(axis=1))


Standard deviation: [4.79152144 8.91650897]


In [23]:
print('Min:' , np.min(heights, axis=1))


Min: [178 170]


In [24]:
print('25th percentile:' , np.percentile(heights, 25, axis=1))


25th percentile: [181.  171.5]


In [25]:
print('Median:', np.median(heights, axis=1))


Median: [185. 176.]


In [26]:
print('75th percentile:', np.percentile(heights, 75, axis=1))


75th percentile: [187. 187.]


In [27]:
print('Max:', np.max(heights, axis=1))


Max: [194 194]


In [29]:
print(np.prod(heights, axis=1))


[8763907890748090624 2098430884410425344]


In [30]:
print(np.var(heights, axis=1))


[22.95867769 79.50413223]


In [31]:
print(np.argmin(heights, axis=1))


[4 4]


In [32]:
print(np.argmax(heights, axis=1))


[0 2]
