In [2]:
import numpy as np


In [4]:
a = np.array([0, 1, 2, 3])
print(a)


[0 1 2 3]


In [9]:
print('a[0] =', a[0])
print('a[1] =', a[1])
print('a[2] =', a[2])
print('a[-1] =', a[-1])


a[0] = 0
a[1] = 1
a[2] = 2
a[-1] = 3


In [11]:
b = np.random.randint(0, 10, (3, 5))
print(b)


[[3 7 3 3 1]
 [9 5 5 7 1]
 [6 9 8 9 6]]


In [23]:
print('b[1,1] =', b[1, 1])
print('b[2,3] =', b[2, 3])
if b[0, 1] == b[1, 3] :
    print('b[0, 1] = b[1, 3]')
if b[1, 1] != b[1, 3] :
    print('not equal')


b[1,1] = 5
b[2,3] = 9
b[0, 1] = b[1, 3]
not equal


In [28]:
b[0, 0] = 5.1
print('b[0, 0] =', b[0, 0])
print(b)


b[0, 0] = 5
[[5 7 3 3 1]
 [9 5 5 7 1]
 [6 9 8 9 6]]


In [29]:
print(a[:3])


[0 1 2]


In [30]:
print(a[1:3])


[1 2]


In [31]:
print(a[::-1])


[3 2 1 0]


In [33]:
c = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8],
                [9, 10, 11]])
print(c)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [40]:
print(c[:2, 1:])
print(c[0:2, 1:])


[[1 2]
 [4 5]]
[[1 2]
 [4 5]]


In [46]:
print(c[0:4, ::2])


[[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]]


In [55]:
print(c[:4, 2])
print(c[:3, 1])


[ 2  5  8 11]
[1 4 7]


In [58]:
print(c[2, :])
print(c[2])
print(c[:, 2])


[6 7 8]
[6 7 8]
[ 2  5  8 11]


In [59]:
print(c[:, 1])


[ 1  4  7 10]


In [60]:
d = np.array([  [0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])
print(d)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [64]:
sub_d = d[1:3, 1:]
print(sub_d)


[[4 5]
 [7 8]]


In [66]:
sub_d[0, 1] = 10
print(sub_d)


[[ 4 10]
 [ 7  8]]


In [67]:
print(d)


[[ 0  1  2]
 [ 3  4 10]
 [ 6  7  8]]


In [71]:
sub_copy_d = d[2:4, 1:].copy()
sub_copy_d[0, 0] = 10
print(sub_copy_d)

print(d)


[[10  8]]
[[ 0  1  2]
 [ 3  4 10]
 [ 6  7  8]]


In [76]:
e = np.arange(16)
print(e)
print(e.reshape(4, 4))
print(e.reshape(16,1))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]


In [78]:
f = np.arange(12)
print(f.reshape(2, -1, 3))


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [80]:
g = np.array([  [0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])
print(g)
print(g.reshape(-1))


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
