In [2]:
import numpy as np
np.__version__


'2.0.2'

In [3]:
np.array([1, 2, 3])


array([1, 2, 3])

In [5]:
np.array([ [1, 2],
            [3, 4],
            [5, 6]])


array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
np.array([  [['000', '001'],['010','011']],
            [['100','101'],['110','111']]])


array([[['000', '001'],
        ['010', '011']],

       [['100', '101'],
        ['110', '111']]], dtype='<U3')

In [8]:
np.zeros(3)


array([0., 0., 0.])

In [9]:
np.ones((2,3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.full((3,2), 'golabi')


array([['golabi', 'golabi'],
       ['golabi', 'golabi'],
       ['golabi', 'golabi']], dtype='<U6')

In [16]:
np.arange(0, 21, 5)


array([ 0,  5, 10, 15, 20])

In [17]:
np.linspace(0, 20, 5)


array([ 0.,  5., 10., 15., 20.])

In [18]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.empty(3)


array([2.35541533e-312, 2.05833592e-312, 2.22809558e-312])

In [21]:
np.random.random(3)


array([0.19535446, 0.12884938, 0.20455792])

In [22]:
np.random.randint(0, 10, (3, 3))


array([[6, 8, 3],
       [9, 3, 1],
       [0, 1, 8]], dtype=int32)

In [23]:
np.random.normal(0, 1, (2, 3))


array([[ 2.03735856,  0.57594311, -0.9230124 ],
       [-0.31693378, -2.07969364,  1.52804109]])

In [25]:
a = np.random.randint(0, 10, (2, 3))
np.full_like(a, 31)


array([[31, 31, 31],
       [31, 31, 31]], dtype=int32)

In [26]:
np.array([False, True], dtype= 'bool_')


array([False,  True])

In [27]:
np.array([1, 2, 3.14], dtype='int_')


array([1, 2, 3])

In [29]:
np.array([2.71, 3.1415], dtype='float64')


array([2.71  , 3.1415])

In [31]:
np.array([255], dtype='uint8')


array([255], dtype=uint8)

In [32]:
np.array(['Hello', 'World'], dtype='str_')


array(['Hello', 'World'], dtype='<U5')

In [41]:
a = np.array(   [[1, 2],
                [3, 4],
                [5, 6]], dtype='float64')
print(a)


[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [42]:
print('number of dimensions:', a.ndim) #تعداد ابعاد ارایه


number of dimensions: 2


In [46]:
print('shape:', a.shape) #اندازه ابعاد آرایه


shape: (3, 2)


In [47]:
print('size:' , a.size) #تعداد خانه های آرایه.


size: 6


In [48]:
print('dtype:', a.dtype) #نوع داده آرایه.


dtype: float64


In [49]:
c = np.array(['h', 'e', 'l', 'l', 'o'])


In [50]:
print(c)


['h' 'e' 'l' 'l' 'o']


In [51]:
print(c.itemsize, 'bytes')


4 bytes


In [52]:
print(c.nbytes, 'bytes')


20 bytes
