In [1]:
import numpy as np


In [2]:
arr = np.array([5, 2, 3, 4, 1])
print('Sorted Array:', np.sort(arr))
print('Original Array:', arr)


Sorted Array: [1 2 3 4 5]
Original Array: [5 2 3 4 1]


In [3]:
arr.sort()
print(arr)


[1 2 3 4 5]


In [5]:
arr = np.array([5, 2, 3, 4, 1])
idx = np.argsort(arr)
print(idx)


[4 1 2 3 0]


In [6]:
arr[idx]


array([1, 2, 3, 4, 5])

In [7]:
arr2d = np.random.randint(0, 10, (4, 5))
print(arr2d)


[[8 7 8 9 3]
 [8 1 1 6 5]
 [1 8 1 1 1]
 [1 9 8 0 7]]


In [8]:
np.sort(arr2d, axis=0)


array([[1, 1, 1, 0, 1],
       [1, 7, 1, 1, 3],
       [8, 8, 8, 6, 5],
       [8, 9, 8, 9, 7]], dtype=int32)

In [9]:
np.sort(arr2d, axis=1)


array([[3, 7, 8, 8, 9],
       [1, 1, 5, 6, 8],
       [1, 1, 1, 1, 8],
       [0, 1, 7, 8, 9]], dtype=int32)

In [10]:
np.partition(arr2d, 2, axis=1)


array([[3, 7, 8, 8, 9],
       [1, 1, 5, 6, 8],
       [1, 1, 1, 1, 8],
       [0, 1, 7, 8, 9]], dtype=int32)