In [1]:
import numpy as np


In [2]:
a = np.array([0, 1, 2, 3])
b = np.array([2, 2, 2, 2])
a * b


array([0, 2, 4, 6])

In [3]:
a * 2


array([0, 2, 4, 6])

In [4]:
a = np.arange(12).reshape(3, 4)
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
b = np.array([3, 2, 1, 0])
print(b)
c = np.array([3, 2, 1]).reshape(3, 1)
print(c)


[3 2 1 0]
[[3]
 [2]
 [1]]


In [26]:
a * b


array([[ 0,  2,  2,  0],
       [12, 10,  6,  0],
       [24, 18, 10,  0]])

In [27]:
a * c


array([[ 0,  3,  6,  9],
       [ 8, 10, 12, 14],
       [ 8,  9, 10, 11]])

In [28]:
a + b


array([[ 3,  3,  3,  3],
       [ 7,  7,  7,  7],
       [11, 11, 11, 11]])

In [29]:
a + c


array([[ 3,  4,  5,  6],
       [ 6,  7,  8,  9],
       [ 9, 10, 11, 12]])