In [1]:
import numpy as np


In [2]:
t = np.array([  [10, 12, 11, 17, 15, 11, 14],
                [13, 15, 18, 21, 19, 18, 17],
                [18, 20, 21, 19, 23, 24, 22],
                [20, 23, 19, 21, 25, 22, 21]])


In [3]:
t[(t >= 15) & (t <= 20)]


array([17, 15, 15, 18, 19, 18, 17, 18, 20, 19, 20, 19])

In [4]:
print('میانگین دمای هوا در روزهای گرم‌تر از ۲۰ درجه:', t[t > 20].mean())
print('میانه دمای هوا در روزهای سردتر از ۲۰ و گرم‌تر از ۱۵ درجه:', np.median(t[(t > 15) & (t < 20)]))


میانگین دمای هوا در روزهای گرم‌تر از ۲۰ درجه: 22.3
میانه دمای هوا در روزهای سردتر از ۲۰ و گرم‌تر از ۱۵ درجه: 18.0


In [5]:
calendar = np.arange(4*7).reshape(4, 7)
holidays = (calendar%7 >= 5) # آرایه بولی متناظر روزهای آخر هفته (پنج‌شنبه و جمعه)
first_mid = (calendar < 2*7) # آرایه بولی متناظر روزهای دو هفته اول اردیبهشت
print('میانه دمای روزهای آخرِ هفته کل ماه:', np.median(t[holidays]))
print('میانه دمای دو هفته نخست ماه:', np.median(t[first_mid]))
print('میانگین دمای روزهای آخرِ هفته در دو هفته پایانی ماه:', np.mean(t[~first_mid & holidays]))


میانه دمای روزهای آخرِ هفته کل ماه: 19.5
میانه دمای دو هفته نخست ماه: 15.0
میانگین دمای روزهای آخرِ هفته در دو هفته پایانی ماه: 22.25


In [10]:
a = np.array([1, 2, 4, 8, 16, 32])
ind = [1, 3, 5]
a[ind] ** 2


array([   4,   64, 1024])

In [11]:
ind = np.array([[2, 3],
                [4, 1]])
a[ind]


array([[ 4,  8],
       [16,  2]])

In [13]:
a = np.arange(12).reshape(4, 3)
print(a)
row = np.array([0, 2, 3, 2])
col = np.array([0, 2, 1, 0])
a[row, col]


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([ 0,  8, 10,  6])

In [14]:
a[row[:, np.newaxis], col]
#گذاشتن np.newaxis در جایی از براکت، به معنای اضافه کردن یک بُعد با اندازه‌ی ۱ به آرایه در آن‌جاست. برای مثال row[:, np.newaxis] معادل است با row.reshape(4, 1)


array([[ 0,  2,  1,  0],
       [ 6,  8,  7,  6],
       [ 9, 11, 10,  9],
       [ 6,  8,  7,  6]])

In [15]:
a = np.array([2, 1, 3, 4, 5])
a[a%2 == 0] *= 10
print(a)


[20  1  3 40  5]


In [16]:
a[[1, 1, 2, 4]] *= 10
print(a)


[20 10 30 40 50]


In [17]:
np.add.at(a, [0, 0, 0, 1, 1, 2], 5)
print(a)
#همان‌طور که از خروجی به‌دست‌آمده استنباط می‌شود، در این حالت مقدار خانه‌ی اول (نمایه ‍0) ۳ مرتبه، مقدار خانه‌ی دوم (نمایه 1) ۲ مرتبه و مقدار خانه‌ی سوم (نمایه 3) ۱ مرتبه با عدد 5 جمع شده اند.


[35 20 35 40 50]
