In [1]:
import numpy as np


In [2]:
a = np.array([1, 10, -5, -9, -19])
a < 8


array([ True, False,  True,  True,  True])

In [6]:
a == np.sqrt(a ** 2)


array([ True,  True,  True,  True,  True])

In [7]:
t = np.array([  [10, 12, 11, 17, 15, 11, 14],
                [13, 15, 18, 21, 19, 18, 17],
                [18, 20, 21, 19, 23, 24, 22],
                [20, 23, 19, 21, 25, 22, 21]])


In [8]:
t > 20


array([[False, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False],
       [False, False,  True, False,  True,  True,  True],
       [False,  True, False,  True,  True,  True,  True]])

In [12]:
np.count_nonzero(t > 20)


10

In [13]:
np.sum(t > 20, axis=1)


array([0, 1, 4, 5])

In [14]:
np.any(t > 30)


np.False_

In [15]:
np.all(t >= 10)


np.True_

In [18]:
np.sum((t >= 15) & (t <= 20))


np.int64(12)

In [21]:
np.sum(~((t < 15) | (t > 20)))


np.int64(12)