In [1]:
import numpy as np


In [3]:
a = np.array([7, 3, 11, 13, 5])


In [4]:
def insertion_sort(a):
    for i in range(len(a)):
        j = i
        while j > 0 and a[j] < a[j-1]:
            a[j], a[j-1] = a[j-1], a[j]
            j -= 1


In [6]:
insertion_sort(a)
print(a)


[ 3  5  7 11 13]


In [7]:
b = np.array([5, 2, 9, 4, 1])
np.sort(b)


array([1, 2, 4, 5, 9])

In [8]:
b.sort()
print(b)


[1 2 4 5 9]


In [10]:
a = np.random.randint(0, 10, (4, 5))
print(a)


[[5 8 5 4 1]
 [0 7 0 2 6]
 [8 5 6 6 1]
 [3 7 4 6 5]]


In [11]:
np.sort(a, axis=0)


array([[0, 5, 0, 2, 1],
       [3, 7, 4, 4, 1],
       [5, 7, 5, 6, 5],
       [8, 8, 6, 6, 6]], dtype=int32)

In [12]:
np.sort(a, axis=1)


array([[1, 4, 5, 5, 8],
       [0, 0, 2, 6, 7],
       [1, 5, 6, 6, 8],
       [3, 4, 5, 6, 7]], dtype=int32)

In [13]:
np.partition(a, 2, axis=1)


array([[1, 4, 5, 5, 8],
       [0, 0, 2, 6, 7],
       [1, 5, 6, 6, 8],
       [3, 4, 5, 6, 7]], dtype=int32)

In [14]:
a = np.array([5, 2, 7, 3, 1])
ind = np.argsort(a)
print(ind)


[4 1 3 0 2]


In [15]:
def my_sort(a):
    if len(a) == 1:
        return
    mid = len(a)//2
    a.partition(mid)
    my_sort(a[:mid])
    my_sort(a[mid:])


In [16]:
a = np.array([3, 5, 1, 4, 2])
my_sort(a)
print(a)


[1 2 3 4 5]


In [ ]:
#جبر خطی


In [17]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print('x =', x)
print('y =', y)


x = [1 2 3]
y = [4 5 6]


In [18]:
np.matmul(x,y)


np.int64(32)

In [19]:
a = np.random.randint(1, 10, (3, 2))
b = np.random.randint(1, 10, (2, 3))
print(a)
print(b)


[[5 9]
 [2 1]
 [9 6]]
[[3 3 1]
 [6 1 4]]


In [20]:
np.matmul(x, a)


array([36, 29])

In [21]:
np.matmul(b, x)


array([12, 20])

In [22]:
np.matmul(a, b)


array([[69, 24, 41],
       [12,  7,  6],
       [63, 33, 33]], dtype=int32)

In [25]:
print(x @ y)
print(a.dot(b))
print(b.dot(a))


32
[[69 24 41]
 [12  7  6]
 [63 33 33]]
[[30 36]
 [68 79]]


In [26]:
from numpy.linalg import inv, det


In [28]:
a = np.random.randn(4, 4)
print(a)


[[-1.37804966  1.18560773 -0.12100634 -0.30973878]
 [ 0.99284356 -1.62133867  0.52912754 -0.2830896 ]
 [-0.02765328  0.74698045 -0.15503724 -1.22748326]
 [-0.05414147  0.20288242  2.51522288 -0.08759477]]


In [29]:
det(a)


np.float64(4.636711435478373)

In [30]:
inv(a)


array([[-1.22191316, -0.670102  ,  0.45501004,  0.11023026],
       [-0.67606789, -0.91808644,  0.36924551,  0.18337266],
       [ 0.01479614,  0.04052059, -0.04071386,  0.38725701],
       [-0.38575967, -0.54871975, -0.59508036,  0.06019496]])