In [2]:
import numpy as np


In [3]:
a = np.random.randint(0, 10, 4) # آرایه‌ای شامل 4 عضو تصادفی در بازه 0 تا 9
b = np.random.randint(0, 10, 4) # آرایه‌ای شامل 4 عضو تصادفی در بازه 0 تا 9
print('a =', a)
print('b =', b)

def cal_sum(a, b) :
    output = np.empty(len(a), dtype='int_')
    for i in range(len(a)):
        output[i] = a[i] + b[i]
    return output

print(cal_sum(a, b))


a = [5 7 7 6]
b = [1 5 3 8]
[ 6 12 10 14]


In [4]:
big_size = 10*1000*1000
a = np.random.randint(0, 10, big_size)
b = np.random.randint(0, 10, big_size)
%timeit cal_sum(a, b)


3.21 s ± 90.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%timeit np.add(a, b)


19.1 ms ± 215 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
a = np.random.randint(0, 10, 4)
b = np.random.randint(0, 10, 4)
print(np.add(a, b)) # قالب قبلی
print(a + b) # استفاده از عملگر معادل
print(np.subtract(a, b))
print(np.multiply(a, b))


[11 13  5 10]
[11 13  5 10]
[5 5 5 0]
[24 36  0 25]


In [15]:
print(np.abs(a))
print(np.sqrt(b))
print(np.square(a))
print(np.isnan(b))


[8 9 5 5]
[1.73205081 2.         0.         2.23606798]
[64 81 25 25]
[False False False False]
